/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2021-07-04 22:57:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.sql.*;

public final class status_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/connection.jsp", Long.valueOf(1625432729752L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html>\r\n");
      out.write("<body bgcolor=\"MediumSeaGreen \">\r\n");
      out.write("<br><br>\r\n");
      out.write("<h1 align=\"center\" style=\"color:white;\">Appointment Application</h1>\r\n");
      out.write("\r\n");
      out.write("<h1 align=\"center\">\r\n");
      out.write("<a href=\"Patient_home.html\">Patient Home</a> |\r\n");
      out.write("<a href=\"profile.jsp\">Profile</a> |\r\n");
      out.write("<a href=\"apply.jsp\">Appointment</a> |\r\n");
      out.write("<a href=\"status.jsp\">Status</a> |\r\n");
      out.write("<a href=\"index.html\">Logout</a>\r\n");
      out.write("</h1>\r\n");
      out.write("<br><br><br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');

Connection con  = null;
PreparedStatement ps = null;

Class.forName("com.mysql.cj.jdbc.Driver");
String url="jdbc:mysql://localhost:3306/myfirstsqleexemple";
String user = "root";
String pass = "Root";
con  = DriverManager.getConnection(url, user, pass);

      out.write("\r\n");
      out.write("\r\n");
      out.write("<table border=\"3\" width =\"1200\" height=\"200\" cellpadding=\"40\" align =\"center\">\r\n");
      out.write("<tr><td> ID</td><td> Patient </td><td>Date</td><td>Time</td><td>Specialisation</td><td>Status</td><td>Doctor</td></tr>\r\n");
      out.write("\r\n");

int id=(Integer)session.getAttribute("ID");
ps = con.prepareStatement("select*from appointment where aid=?");
ps.setInt(1,id);
ResultSet rs = ps.executeQuery();
while(rs.next()){

      out.write("\r\n");
      out.write("<tr><td>");
      out.print(rs.getInt(1) );
      out.write("</td><td>");
      out.print(rs.getString(2) );
      out.write("</td>\r\n");
      out.write("<td>");
      out.print(rs.getString("doa") );
      out.write("</td><td>");
      out.print(rs.getString("toa") );
      out.write("\r\n");
      out.write("</td><td>");
      out.print(rs.getString("specialisation") );
      out.write("</td><td>");
      out.print(rs.getString("Status") );
      out.write("</td>\r\n");
      out.write("<td>");
      out.print(rs.getString("Doctor") );
      out.write("</td></tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t");

}

      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
